import { apiError, apiOk } from "@/lib/api/response";
import { getSessionArea } from "@/lib/auth/session-area";
import { getMerchantStoreForUser } from "@/lib/merchant/data";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";

type Role = "cliente" | "venditore" | "corriere";
const roleForArea=(a:string):Role|null=>a==="customer"?"cliente":a==="merchant"?"venditore":a==="courier"?"corriere":null;

async function authorize(orderId:string,userId:string,area:string){
 const role=roleForArea(area); if(!role)return{error:apiError("FORBIDDEN","Area non autorizzata.",403)};
 const admin=createAdminSupabaseClient();
 const {data:order}=await admin.from("ordini").select("id,numero,negozio_id,negozio_nome,cliente_user_id,cliente_nome,cliente_cognome,modalita,spedizione_carrier,spedizione_servizio").eq("id",orderId).maybeSingle();
 if(!order)return{error:apiError("NOT_FOUND","Ordine non trovato.",404)};
 if(order.modalita!=="spedizione"||order.spedizione_carrier!=="locale"||order.spedizione_servizio!=="locale")return{error:apiError("NOT_LOCAL_DELIVERY","La comunicazione è disponibile per le consegne locali.",422)};
 if(role==="cliente"){if(order.cliente_user_id!==userId)return{error:apiError("FORBIDDEN","Non puoi accedere a questa conversazione.",403)}}
 else if(role==="venditore"){const store=await getMerchantStoreForUser(userId,order.negozio_id);if(!store.data)return{error:apiError("FORBIDDEN","Non puoi accedere a questa conversazione.",403)}}
 else {const {data:d}=await admin.from("corrieri_locali").select("corriere_user_id").eq("ordine_id",orderId).maybeSingle();if(d?.corriere_user_id!==userId)return{error:apiError("FORBIDDEN","Questa consegna non è assegnata al tuo profilo.",403)}}
 return{admin,order,role};
}
export async function GET(_:Request,c:{params:Promise<{ordineId:string}>}){const s=await getSessionArea();if(!s)return apiError("UNAUTHORIZED","Devi accedere al tuo account.",401);const {ordineId}=await c.params;const a=await authorize(ordineId,s.user.id,s.area);if("error"in a)return a.error;const {data,error}=await a.admin.from("ordine_comunicazioni").select("id,ordine_id,mittente_user_id,mittente_ruolo,mittente_nome,corpo,created_at,ordine_comunicazioni_letture!left(user_id)").eq("ordine_id",ordineId).order("created_at",{ascending:true});if(error)return apiError("READ_ERROR","Impossibile caricare la conversazione.",500);return apiOk({ordine:{id:a.order.id,numero:a.order.numero,negozioNome:a.order.negozio_nome},messaggi:(data??[]).map((r:any)=>({...r,letto:(r.ordine_comunicazioni_letture??[]).some((x:any)=>x.user_id===s.user.id)}))});}
export async function POST(req:Request,c:{params:Promise<{ordineId:string}>}){const s=await getSessionArea();if(!s)return apiError("UNAUTHORIZED","Devi accedere al tuo account.",401);const {ordineId}=await c.params;const a=await authorize(ordineId,s.user.id,s.area);if("error"in a)return a.error;const b=await req.json().catch(()=>null);const corpo=typeof b?.corpo==="string"?b.corpo.trim().slice(0,2000):"";if(!corpo)return apiError("VALIDATION_ERROR","Scrivi un messaggio.",422);const md=s.user.user_metadata??{};const nome=String(md.nome??"").trim()||String(md.full_name??"").trim()||([a.role==="cliente"?a.order.cliente_nome:"",a.role==="cliente"?a.order.cliente_cognome:""].filter(Boolean).join(" "))||a.order.negozio_nome||(a.role==="corriere"?"Corriere":"Utente");const{data,error}=await a.admin.from("ordine_comunicazioni").insert({ordine_id:ordineId,mittente_user_id:s.user.id,mittente_ruolo:a.role,mittente_nome:nome,corpo}).select("id,ordine_id,mittente_user_id,mittente_ruolo,mittente_nome,corpo,created_at").single();if(error)return apiError("SAVE_ERROR","Impossibile inviare il messaggio.",500);return apiOk({messaggio:data});}
export async function PATCH(req:Request,c:{params:Promise<{ordineId:string}>}){const s=await getSessionArea();if(!s)return apiError("UNAUTHORIZED","Devi accedere al tuo account.",401);const {ordineId}=await c.params;const a=await authorize(ordineId,s.user.id,s.area);if("error"in a)return a.error;const b=await req.json().catch(()=>null);if(b?.azione!=="segna_letti")return apiError("VALIDATION_ERROR","Azione non valida.",422);const{data:rows}=await a.admin.from("ordine_comunicazioni").select("id").eq("ordine_id",ordineId).neq("mittente_user_id",s.user.id);if(rows?.length){const{error}=await a.admin.from("ordine_comunicazioni_letture").upsert(rows.map((x:any)=>({messaggio_id:x.id,user_id:s.user.id})),{onConflict:"messaggio_id,user_id"});if(error)return apiError("READ_ERROR","Impossibile aggiornare i messaggi letti.",500)}return apiOk({ok:true});}