import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on("console", (m) => { if (m.text().includes("[DEBUG]")) console.log("COMP:", m.text()); });
await page.goto("http://localhost:3177/test-editor?w=800&h=600");
await page.getByRole("button", { name: "Ritaglia" }).click();
const box = page.locator("[data-editor-preview] .cursor-move");
await box.waitFor();
await page.locator("[data-editor-preview]").scrollIntoViewIfNeeded();
await page.waitForTimeout(200);
const bb = await box.boundingBox();
const grabX = bb.x + bb.width - 3, grabY = bb.y + bb.height - 3;
await page.mouse.move(grabX, grabY);
await page.mouse.down();
await page.mouse.move(grabX + bb.width * 0.5, grabY + bb.height * 0.5, { steps: 10 });
await page.mouse.up();
await page.waitForTimeout(300);
console.log("data-test-crop:", await box.getAttribute("data-test-crop"));
console.log("style:", await box.getAttribute("style"));
await browser.close();
