begin;

-- Schema base necessario alle migration successive.
-- Le colonne evolutive, gli indici, i trigger, le policy e le FK vengono
-- introdotti dalle migration dedicate che seguono.

create table if not exists public.negozi (
  id                  uuid primary key default gen_random_uuid(),
  nome                text not null,
  categoria           text,
  descrizione         text,
  indirizzo           text,
  telefono            text,
  email               text,
  whatsapp            text,
  sito_web            text,
  facebook            text,
  instagram           text,
  tiktok              text,
  youtube             text,
  immagine            text,
  copertina           text,
  orari               jsonb,
  attivo              boolean default true,
  in_evidenza         boolean default false,
  slug                text,
  citta               text,
  cap                 text,
  provincia           text,
  coordinate          text,
  mostra_telefono     boolean not null default true,
  mostra_indirizzo   boolean not null default true,
  mostra_orari        boolean not null default true,
  accetta_whatsapp    boolean not null default true,
  descrizione_completa text,
  sottocategoria      text,
  created_at          timestamptz default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists public.prodotti (
  id            bigint generated by default as identity primary key,
  negozio_id    uuid,
  nome          text,
  descrizione   text,
  prezzo        numeric,
  categoria     text,
  immagine      text,
  disponibile   boolean default true
);

commit;
