create table if not exists public.pino_memoria (
  id bigint generated by default as identity primary key,
  termine text not null,
  concetto text not null,
  tipo text not null default 'semantica',
  frequenza integer not null default 1 check (frequenza > 0),
  successi integer not null default 0 check (successi >= 0),
  fallimenti integer not null default 0 check (fallimenti >= 0),
  confidence numeric(5,4) not null default 0.5000 check (confidence >= 0 and confidence <= 1),
  ultima_utilizzazione timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pino_memoria_termine_concetto_key unique (termine, concetto)
);

alter table public.pino_memoria enable row level security;

create index if not exists pino_memoria_termine_idx on public.pino_memoria (termine);
create index if not exists pino_memoria_confidence_idx on public.pino_memoria (confidence desc, frequenza desc);

create or replace function public.pino_memoria_touch_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_catalog
as $
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pino_memoria_touch on public.pino_memoria;
create trigger pino_memoria_touch
before update on public.pino_memoria
for each row execute function public.pino_memoria_touch_updated_at();
